### ISSUE TITLE
Donut = experimental Tugboat

### ISSUE THREAD

**Issue by rdela** [11ty/tugboat#8]
As noted in #6, my devDeps update (which I followed up with #7, a package metadata update), I am beginning to noodle around Tugboat 🛟

I brought up some of my guiding questions on [Mastodon](https://mastodon.social/@rdela/112689989457173792): 

> Thinking of extending the Tugboat collection of WebC components
> - What would you like to see most? 
> - A separate collection alongside Tugboat?
> - Integrating more components into Tugboat?
> - What should we consider adding? 
> - Are you using a component library like this already?
> - Looking forward to any upcoming releases? 

I have my own answers to all these questions which I plan to start writing about soon. My overall plan for now in regards to Tugboat (and Eleventy in general) is to keep developing [eleventeen](https://eleventeen.blog/about/) in the open and to start integrating existing Tugboat components there, alongside experimental versions of an additional set of WebC components.

Having found an [abundance of adequate names in the thesaurus](https://mastodon.social/@rdela/112697613687560685) for this new set of experimental add-on components, in typical fashion I went with none of them, instead settling on ✨**Donut**✨, since it is a popular way to refer to the “[life-saving buoy](https://en.wikipedia.org/wiki/Lifebuoy) designed to be thrown to a person in water to provide buoyancy and prevent drowning,” that the “ring buoy” emoji (🛟) depicts, among life guards and water rescue [folx](https://www.merriam-webster.com/dictionary/folx).

> Other names for “lifebuoy” include:
>
> - life preserver
> - life ring
> - lifering
> - lifesaver
> - ring buoy
> - donut
> - safety wheel
> - Perry buoy
> - Kisbee ring

With the hardest problem in software development (other than off by one errors) solved, my first thought with Donut was to get a playground, testbed type situation going. I set [my fork of Tugboat’s `main` branch](https://github.com/rdela/tugboat/tree/main) to build a mirror of https://tugboat.11ty.dev at https://tugboat.netlify.app

Then I set up the [`donut` branch of my fork](https://github.com/rdela/tugboat/tree/donut), where I am making all the new experimental additions and modfications, to build at https://donut--tugboat.netlify.app

Right now there is only one experimental WebC component, [Emoji link](https://donut--tugboat.netlify.app/#emoji-links) ([source](https://github.com/rdela/tugboat/blob/donut/_components/emoji-link.webc), commit [617f094](https://github.com/rdela/tugboat/commit/617f0940a00d92cf1f6bb3f27ddd057447f1a110)) that blends `favicon-link` with `accessible-emoji`. This was borne of trying to link to Tugboat with `favicon-link` only to realize it had no favicon.

I made separate sections for [Donut Features](https://donut--tugboat.netlify.app/#donut-features) and [Tugboat Features](https://donut--tugboat.netlify.app/#tugboat-features), plus [Donut Demos](https://donut--tugboat.netlify.app/#donut-demos) and [Tugboat Demos](https://donut--tugboat.netlify.app/#tugboat-demos), in [`index.webc`](https://github.com/rdela/tugboat/blob/donut/index.webc) even though I added [`emoji-link.webc`](https://github.com/rdela/tugboat/blob/donut/_components/emoji-link.webc) to the same directory, [`_components`](https://github.com/rdela/tugboat/tree/donut/_components).

Lastly, in that same commit, [7da007b](https://github.com/rdela/tugboat/commit/7da007bbd3e995c6d14bb69c87a149914d44e340), I decided to change both light and dark color schemes to help keep myself oriented context switching back and forth, inspired by the color palette of a [chocolate glazed donut with sprinkles](https://duckduckgo.com/?q=chocolate+glazed+donut+with+sprinkles&t=ffab&iax=images&ia=images), [candy sprinkles](https://duckduckgo.com/?t=ffab&q=candy+sprinkles&iax=images&ia=images), and particluarly the pinks and oranges in [this image](https://pxhere.com/en/photo/883692). I also updated some of the metadata to hopefully avoid more confusion than necessary.

The general idea is that this takes any pressure off to integrate experimental components into Tugboat while providing an easy way to pull ones that do interest the Tugboat crowd into projects and Tugboat itself. I have not published anything to npm yet and it appears 11ty has not yet either. Ideal distribution and update mechanisms, starting with how do people update their starters and component setups currently, is something I am very keen to hear more about.

Hope this explains some of my thought process so far. Excited for any and all input.

🛟✨🍩

**Comment by theapplegates** [comment]
Mainly commenting because I think tugboat is underrated. Plus, I remember this site back in the day. State-of-the-art 11ty. 2019.
https://candy-11ty.netlify.app

**Comment by rdela** [comment]
@theapplegates Totally underrated! Feel like we need a marketing push to get the word out to the world.

Thanks for the link to https://github.com/stickhandle/candy-11ty I had not seen it and that looks very cool plus a great place to ponder ideas from. Just looking around your GH profile I found several things for my Eleventy list https://github.com/stars/rdela/lists/eleventy/

My list is no https://11tybundle.dev but it's mine haha. Things I added or saw you also interacted with of note: 

- Eleventy Excellent: Easy to use Eleventy starter, based on the workflow suggested by Andy Bell's buildexcellentwebsit.es - https://github.com/madrilene/eleventy-excellent

- eleventy-base-blog but with Sia's opinions https://github.com/siakaramalegos/11ty-sia-blog

- influenced by now archived https://github.com/Andy-set-studio/hylia

- A high performance blog template from Google based on Malte Ubl's Industrial Empathy https://github.com/google/eleventy-high-performance-blog

- Cactus theme for Astro I hadn't seen before https://github.com/chrismwilliams/astro-theme-cactus

Speaking of Astro I also think https://github.com/HiDeoo/starlight-blog has some thoughtful design and considerate functionality we could learn from.

**Comment by rdela** [comment]
Added a couple commits 

- use [server-only comments](https://www.11ty.dev/docs/languages/webc/#server-only-comments) in emoji-link ([00bfb91](https://github.com/rdela/tugboat/commit/00bfb91a9ccbd8e4cbd7eaaf1c2f04f46d279a1c)) 
- add emoji-link to [donut branch](https://github.com/rdela/tugboat/tree/donut/) from Donut demo, also linked from repo to [Donut demo](https://donut--tugboat.netlify.app) ([a103db9](https://github.com/rdela/tugboat/commit/a103db91354dd61a557a852527067caacfaf3eaf))

**Comment by theapplegates** [comment]
my website is a fork of https://github.com/madrilene/eleventy-excellent , her site is the best in my opinion. You can keep it as is or add to it. My personal site is there at https://paulapplegate.com. The site is not done or even started by any means.
I'm not a developer so maybe you can answer this. Why under certin circumstances does GitHub make meke a pull request instead of updating a fork by just syncing it?
Either way if you want to answer maybe head to the discord server, better yet I will ask. Since Github is probably not the forum to make a thread of questions/answers 
Paul

**Comment by rdela** [comment]
Eleventy Excellent is fabulous, feels like the most complete and actively maintained Eleventy starter out there to me right now, [3.2.0](https://github.com/madrilene/eleventy-excellent/commits/main/) is just out. Much respect to @madrilene

I am in the 11ty Discord, if you want to tag me my handle is rickydelaveaga
